---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: radarr-policy
  namespace: plex
spec:
  imageRepositoryRef:
    name: radarr
  policy:
    semver:
      range: ">=5.27.0"
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: sonarr-policy
  namespace: plex
spec:
  imageRepositoryRef:
    name: sonarr
  policy:
    semver:
      range: ">=4.0.14"
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: prowlarr-policy
  namespace: plex
spec:
  imageRepositoryRef:
    name: prowlarr
  policy:
    semver:
      range: ">=2.3.0"
