apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: radarr
  namespace: plex
spec:
  image: linuxserver/radarr
  interval: 1h

---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: sonarr
  namespace: plex
spec:
  image: linuxserver/sonarr
  interval: 1h

---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: prowlarr
  namespace: plex
spec:
  image: linuxserver/prowlarr
  interval: 1h

---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: overseerr
  namespace: plex
spec:
  image: linuxserver/overseerr
  interval: 1h

---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: qbittorrent
  namespace: plex
spec:
  image: lscr.io/linuxserver/qbittorrent
  interval: 1h

---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: tdarr
  namespace: plex
spec:
  image: ghcr.io/haveagitgat/tdarr
  interval: 1h

---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: tdarr-node
  namespace: plex
spec:
  image: ghcr.io/haveagitgat/tdarr_node
  interval: 1h
