apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - image-policies.yaml
  - image-repositories.yaml
  - image-update-automation.yaml
  - jackett.yaml
  - plex.yaml
  - qbittorrent.yaml
  - qbitmanage.yaml
  - radarr.yaml
  - sonarr.yaml
  - tdarr.yaml
  - overseerr.yaml
  - prowlarr.yaml
  - secret.qbit.yaml
  - secret.ghcr.yaml
  - secret.plex.yaml
