apiVersion: v1
kind: Service
metadata:
  name: port-service-overseerr
  namespace: plex
spec:
  type: NodePort
  selector:
    app: overseerr
  ports:
    - name: overseerr-port
      port: 5055
      targetPort: 5055
      nodePort: 30018

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: overseerr
  namespace: plex
  labels:
    app: overseerr
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: overseerr
  template:
    metadata:
      labels:
        app: overseerr
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1004
        fsGroup: 1004
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL 
      containers:
        - name: overseerr
          image: linuxserver/overseerr:1.35.0
          imagePullPolicy: Always
          ports:
            - containerPort: 5055
          env:
            - name: TZ
              value: "America/Denver"
            - name: LOG_LEVEL
              value: "info"
          volumeMounts:
            - name: overseerr-config
              mountPath: /config
      volumes:
        - name: overseerr-config
          hostPath:
            path: /home/server/docker/overseerr
            type: Directory
