apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: plex
  labels:
    app: prowlarr
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      initContainers:
      - name: flaresolverr
        image: ghcr.io/flaresolverr/flaresolverr:v3.4.6
        imagePullPolicy: Always
        restartPolicy: Always
        ports:
        - containerPort: 8191
        env:
        - name: LOG_LEVEL
          value: "info"
        - name: CAPTCHA_SOLVER
          value: "none"
      containers:
      - name: prowlarr
        image: linuxserver/prowlarr:2.5.2 #  {"$imagepolicy": "plex:prowlarr-policy"}
        env:
        - name: PUID
          value: "1001"
        - name: PGID
          value: "1004"
        - name: TZ
          value: "Etc/UTC"
        ports:
        - containerPort: 9696
        volumeMounts:
        - name: config
          mountPath: /config
      volumes:
      - name: config
        hostPath:
          path: /home/server/docker/prowlarr/
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr-service
  namespace: plex
spec:
  type: NodePort
  selector:
    app: prowlarr
  ports:
    - protocol: TCP
      port: 9696 # Port internal to the cluster
      targetPort: 9696 # Port the container listens on
      nodePort: 30003 # Port accessible from outside (Range: 30000-32767)
