apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployment-restarter-sa
  namespace: plex
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-restarter-role
  namespace: plex
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "patch", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-restarter-binding
  namespace: plex
subjects:
  - kind: ServiceAccount
    name: deployment-restarter-sa
    namespace: plex
roleRef:
  kind: Role
  name: deployment-restarter-role
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: qbittorrent-restarter
  namespace: plex
spec:
  schedule: "0 0 * * 0" # Every Sunday at 00:00
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: deployment-restarter-sa
          containers:
          - name: kubectl
            image: bitnami/kubectl:latest
            command:
            - /bin/sh
            - -c
            - kubectl rollout restart deployment -l app=qbittorrent -n plex
          restartPolicy: OnFailure
