apiVersion: apps/v1
kind: Deployment
metadata:
  name: requestrr
  namespace: plex
  labels:
    app: requestrr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: requestrr
  template:
    metadata:
      labels:
        app: requestrr
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1004
        fsGroup: 1004
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL 
      containers:
        - name: requestrr
          image: darkalfx/requestrr:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4545
              name: webui
              protocol: TCP
          volumeMounts:
            - name: requestrr-config
              mountPath: /root/config
            - name: requestrr-tmp
              mountPath: /root/tmp
      volumes:
        - name: requestrr-config
          hostPath:
            path: /home/server/docker/requestrr
            type: DirectoryOrCreate
        - name: requestrr-tmp
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: requestrr-service
  namespace: plex
  labels:
    app: requestrr
spec:
  type: NodePort
  selector:
    app: requestrr
  ports:
    - name: http
      port: 4545
      targetPort: 4545
      nodePort: 30020
      protocol: TCP
