apiVersion: v1
data:
    claim-token: ENC[AES256_GCM,data:XOrS6/7VPryGkijlULel2q6v7WgKMDPuf3m4LUsvpc3EjEMS,iv:fMbwP0HS1f6f/9NphgQp9SxneCYyLmaNKbevWC1SUFU=,tag:SkpaQ8h9BacDrv9dU3R5XA==,type:str]
kind: Secret
metadata:
    name: plex-secret
    namespace: plex
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1frds4dglkf9tsnz00zf3tgyxf9q7xxqaeeh44p9dgjeqqfl35a2qxcjcfm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDN2JpV2JIN2hqOTd5Y01U
            R2dDTFZ6NHZWcC82RHBjcU0wSFJVWUtuaUdFCnJ3cEl4UnRwam05eVU1YW41U0ty
            YWlHSHVvNm4yZDN0V0JBT1R3cXo4cEUKLS0tIEx2Tm1xREZaQllOMUdRUElYVzgz
            MHZLQ1BjTUVzWGNXVGRQbVVmUnMwQ2cK3dPD+OxQcpysW57y+l5VYXSBa4KItGVp
            IDXL4upiKnww2WxG1pCa5WMoXSK4PIdZskviIt6EteNsz+73HSZZUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-15T04:20:44Z"
    mac: ENC[AES256_GCM,data:T1p44EcLnEqRmYKi4RImiqvfV1Bl2ryUZ9SZpU0wrEhYLZdn9fgrNjXJl1yAeeZCerXmiS4ccwnoB/tEDcBlVecD8xA4KyHeepTgLMgSkI7q4AFJxcxQt3CC0REXGNuP5a7pIjxuXLOpeLYXBazDdELNjC68i0QeFNL+jIyOm0s=,iv:LwBvalmXIiNIh5Y0vBA66F4mEE6lbOfcWwhw91DBHvM=,tag:nRo56mD3H9L15HMhFkJvbQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0