apiVersion: v1
kind: Secret
metadata:
    name: qbit-wireguard-config
    namespace: plex
    labels:
        kustomize.toolkit.fluxcd.io/name: apps
        kustomize.toolkit.fluxcd.io/namespace: flux-system
type: Opaque
stringData:
    wg0.conf: ENC[AES256_GCM,data:ywtmXvit6qfsNYBZPNvIbdBWxLd1DjJ6g5vwDM6bIcySLYKGV8lJBopE4gBGbEHk2gOHWqEWJwgqlnyFVfj117Rg8zjepMgEcl/UMaA4TxB8TzJ6JYlBnIP4bjKDW587tRlzK3Sj/8Eg+rAPy5jFZGVa7sbN5Ozb5g5qBAGlYL5blC/MNQd0y7+d1+dkCpWLpRu0Dhp52+FXLHVtwUJ6BQxzmyI76kbFpFcmxqis6fGD517Dt+876vSQB5UxakKg7wYikvDujCNwWR+m/kHhbFT43dWiuvaucX1GPsGuJsaJaSwUELl/4/qwn8NHw8v92lEGFsaIV3mhylurGF/nIG/fCeGROAZ7oLJ7DQuBJQTmR4ITy9mAuomOf3kCkFBTmtiLLy6PD8Uq9agCT23UTmdmIVczr0on,iv:dIG5pARhku09k4isA8lMQoItCjoOAq3wO1qZp8cTqi4=,tag:6IVOrzWzn0QY9eaiVhIjmw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1frds4dglkf9tsnz00zf3tgyxf9q7xxqaeeh44p9dgjeqqfl35a2qxcjcfm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYS3F5RURPMkw5aCtuaUg0
            VVcwNnRvKzFKN29kelAzcGUzQW4rRDFxVFJzCit3WFhLTDk5eVI3RkNScERGcmt5
            NktUdW1xQVBFK0NaTHp1Nlgwc3JWdFkKLS0tIGpvbi9oeDVTR1JGVE1UUUdEcUw0
            UUpDQmRLNklIS09nTnhPU2pVWmRjdEkKOjGWIgGMyODNIjwNyrOq7GefNRjnOpPp
            zkepzlYDFiTBkEtyuDQvwVp1yqhTBtEihq2CCI1tdNitvc8rrqf3Tg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-04T07:52:14Z"
    mac: ENC[AES256_GCM,data:KG4SfB4GcAKYV4S3wHD23YkONHcYXPKTn9cKOBtKQMLrwLzvhnxzN1hxv9Gvlm3UveIL0I07mdqTsrd2OOA4oJ05rYtQnTB1gW242daIzPdBf7P27geKwRSdMmYTO/06Gq9D2v5+TQ6aXgQn8VBhbFv6ZpB1g+kT2qp1KHzkLDc=,iv:/TDuK8B2zugPd+cXQh0ZnYly0rHR/4BG3745Eg1W8sc=,tag:+uf7+DoJHj21YYQvEKTLzQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0