apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: teslamate
  namespace: monitoring
spec:
  interval: 15m
  releaseName: teslamate
  chart:
    spec:
      chart: teslamate
      version: 7.2.0
      sourceRef:
        kind: HelmRepository
        name: teslamate
        namespace: flux-system
  install:
    createNamespace: true
  values:
    podLabels:
      exposed: nodeport
    image:
      repository: teslamate/teslamate
      tag: "4.1.1"
    env:
      - name: TZ
        value: UTC
      - name: DATABASE_HOST
        value: '{{ include "common.names.fullname" .}}-postgresql'
      - name: DATABASE_USER
        value: postgres
      - name: DATABASE_PASS
        value: "{{ .Values.postgresql.auth.postgresPassword }}"
      - name: DATABASE_NAME
        value: "{{ .Values.postgresql.auth.database }}"
      - name: DISABLE_MQTT
        value: "false"
      - name: MQTT_HOST
        value: "mosquitto"

      - name: ENCRYPTION_KEY
        valueFrom:
          secretKeyRef:
            name: teslamate-secret
            key: encryption-key

    ingress:
      main:
        enabled: false

    persistence:
      import:
        enabled: false

    extraVolumes:
      - name: postgres-data
        hostPath:
          path: /root/docker/teslamate/teslamate-db
          type: DirectoryOrCreate
              
    extraVolumeMounts:
      - name: postgres-data
        mountPath: /bitnami/postgresql




    postgresql:
      enabled: true
      image:
        repository: bitnami/postgresql
        tag: "17.6.0"
        digest: ""
        pullPolicy: IfNotPresent
      primary:
        persistence:
          enabled: false
          
      auth:
        existingSecret: teslamate-postgresql
        database: teslamate
        persistence:
          enabled: true
          existingClaim: teslamate-postgres-pvc
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: monitoring
spec:
  interval: 15m
  releaseName: mosquitto
  chart:
    spec:
      chart: mosquitto
      version: 2.4.1
      sourceRef:
        kind: HelmRepository
        name: mosquitto
        namespace: flux-system
  values:
    service:
      type: ClusterIP
      externalTrafficPolicy: null
      annotations: {}

---

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: loki
      version: 6.46.0
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
  install:
    createNamespace: true
  values:
    deploymentMode: SingleBinary
    backend:
      replicas: 0
    read:
      replicas: 0
    write:
      replicas: 0
    ruler:
      enabled: false
    ingester:
      wal:
        enabled: false

    singleBinary:
      extraVolumes:
        - name: var-loki
          emptyDir:
            sizeLimit: 10Gi
      extraVolumeMounts:
        - name: var-loki
          mountPath: /var/loki
      persistence:
        enabled: false
    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      storage:
        type: filesystem
        bucketNames:
          chunks: loki-chunks
          ruler: loki-ruler
          admin: loki-admin
        filesystem:
          chunks_directory: /var/loki/chunks
          rules_directory: /var/loki/rules
      schemaConfig:
        configs:
          - from: "2024-01-01"
            store: tsdb
            object_store: filesystem
            schema: v13
            index:
              prefix: loki_index_
              period: 24h
    gateway:
      enabled: true
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 256Mi

---

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
  namespace: monitoring
spec:
  chart:
    spec:
      chart: promtail
      version: 6.17.1
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
  interval: 10m
  values:
    config:
      clients:
        - url: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push
    daemonset:
      enabled: true
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi

---

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dcgm-exporter
  namespace: monitoring
spec:
  interval: 15m
  releaseName: dcgm-exporter
  chart:
    spec:
      chart: dcgm-exporter
      version: 4.8.3
      sourceRef:
        kind: HelmRepository
        name: dcgm-exporter
        namespace: flux-system
  values:
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: prometheus-community

---

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-community
  namespace: monitoring
spec:
  interval: 15m
  releaseName: prometheus-community
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 88.5.2
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    defaultRules:
      rules:
        etcd: false
        kubeControllerManager: false
        kubeProxy: false
        kubeSchedulerAlerting: false
        kubeSchedulerRecording: false
        general: false
    grafana:
      podLabels:
        exposed: nodeport
      deploymentStrategy:
        type: Recreate
      initChownData:
        enabled: true
      enabled: true
      sidecar:
        datasources:
          enabled: false
        dashboards:
          enabled: false
          label: grafana_dashboard
          labelValue: "1"
          searchNamespace: ALL
        serviceMonitorSelectorNilUsesHelmValues: false
      extraVolumes:
        - name: grafana-host
          hostPath:
            path: /home/server/docker/monitoring/grafana
            type: Directory

      extraVolumeMounts:
        # Dashboards (JSON files)
        - name: grafana-host
          mountPath: /var/lib/grafana/dashboards
          subPath: dashboards

        # Datasources provisioning
        - name: grafana-host
          mountPath: /etc/grafana/provisioning/datasources
          subPath: provisioning/datasources

        # Dashboard provisioning configs
        - name: grafana-host
          mountPath: /etc/grafana/provisioning/dashboards
          subPath: provisioning/dashboards

        - name: grafana-host
          mountPath: /etc/grafana/provisioning/alerting
          subPath: provisioning/alerting
          readOnly: false

      admin:
        existingSecret: "grafana-admin"
        userKey: admin-user
        passwordKey: admin-password

      ingress:
        enabled: false
    prometheus-node-exporter:
          prometheus:
            monitor:
              relabelings:
                - action: replace
                  regex: (.+)
                  replacement: $1
                  sourceLabels:
                    - __meta_kubernetes_endpoint_node_name
                  targetLabel: node
---

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-adapter
  namespace: monitoring
spec:
  interval: 15m
  releaseName: prometheus-adapter
  chart:
    spec:
      chart: prometheus-adapter
      version: "5.3.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    prometheus:
      url: http://prometheus-community-kube-prometheus.monitoring.svc
      port: 9090
    rules:
      default: false
      
      resource:
        cpu:
          containerQuery: |
            sum by (<<.GroupBy>>) (
              rate(container_cpu_usage_seconds_total{container!="",container!="POD",<<.LabelMatchers>>}[3m])
            )
          nodeQuery: |
            sum by (<<.GroupBy>>) (
              rate(node_cpu_seconds_total{mode!="idle",mode!="iowait",mode!="steal",<<.LabelMatchers>>}[3m])
            )
          resources:
            overrides:
              node:
                resource: node
              namespace:
                resource: namespace
              pod:
                resource: pod
          containerLabel: container
        memory:
          containerQuery: |
            sum by (<<.GroupBy>>) (
              container_memory_working_set_bytes{container!="",container!="POD",<<.LabelMatchers>>}
            )
          nodeQuery: |
            sum by (<<.GroupBy>>) (
              node_memory_MemTotal_bytes{<<.LabelMatchers>>}
              - node_memory_MemFree_bytes{<<.LabelMatchers>>}
              - node_memory_Buffers_bytes{<<.LabelMatchers>>}
              - node_memory_Cached_bytes{<<.LabelMatchers>>}
            )
          resources:
            overrides:
              node:
                resource: node
              namespace:
                resource: namespace
              pod:
                resource: pod
          containerLabel: container
