apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: teslamate
  namespace: flux-system
spec:
  interval: 6h
  url: https://geek-cookbook.github.io/charts/

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: mosquitto
  namespace: flux-system
spec:
  interval: 6h
  url: https://storage.googleapis.com/t3n-helm-charts
  
---

apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: flux-system
spec:
  interval: 1h
  url: https://prometheus-community.github.io/helm-charts
  
---

apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana-charts
  namespace: flux-system
spec:
  interval: 1h
  url: https://grafana.github.io/helm-charts
  
---

apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: dcgm-exporter
  namespace: flux-system
spec:
  interval: 1h
  url: https://nvidia.github.io/dcgm-exporter/helm-charts