apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
  - helmrepo.yaml
  - teslamate-nodeport.yaml
  - teslamate-pv.yaml
  - secret.teslamate.yaml
  - secret.postgresql.yaml
  - homarr.yaml
  - image-policies.yaml
  - image-repositories.yaml
  - image-update-automation.yaml
  - grafana-nodeport.yaml
  - secret.grafana.yaml
  - world-monitor.yaml