apiVersion: v1
data:
    encryption-key: ENC[AES256_GCM,data:TNV+agSW0QBgFIDZI0h2LXpWmK26V8MEz+90oxMa7KmiEkI7svkTnmZ0EnKjNiNP3ve2aGwxKs6tUtawKxm1d8mGmntwF0dThM4WBDsNOZL9oC9kfka1ig==,iv:OQbKwqGj2pJG79Q1kHxpyp5ErffIVpMCAD3HnT1LU/w=,tag:J8dX/bPx8n+8pFd95H3Z/w==,type:str]
kind: Secret
metadata:
    name: teslamate-secret
    namespace: monitoring
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1frds4dglkf9tsnz00zf3tgyxf9q7xxqaeeh44p9dgjeqqfl35a2qxcjcfm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiWG9qT3RnczFBMjFNaGR5
            cUJ4RWoycUk2RTlTcDZUZHpIdzkwQllmOHkwCkdNaHdzb2Z5bjRXL1EzSnppOFZM
            dW5vSVR0MWY5STVjY1VRK3NvOUpqUGcKLS0tIFVqQi9iUGtod1pzY3dTUHFiZTNN
            aUJIRGRjYU1QcWNiRjVrN0JVU0JiNU0KA4dgk1VcEbGGxTL3KixUMJ9IxMf5I2Yj
            s5D8IWYdw16vUDuUqJXOOYyaQgR2qJPcbfTgI5JSPP/gLh/dUr2cPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-23T01:21:13Z"
    mac: ENC[AES256_GCM,data:qeVD3Rdwm0pMnbya/oFne6MJpZ5hd3RaaGLXh+htS3P0KQ18pEEuf1H1ADycldEoTz6VRj0p6TjrGgpRxGRg26tsi+FRmuZeEaibealcB11ffcwpuCx6plMgHp/iU/7A1/XGyLm6Kz1YCwRsSBjD1L482wc7NHImw1586/Xsplg=,iv:v91fx4hzDKFWj30SDdptZe3YzDYFMoxGr6tMWjp7PSY=,tag:hlljghP0OFFb4HAs0a7sEg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
