apiVersion: v1
data:
    postgres-password: ENC[AES256_GCM,data:N31pyaZohhlzEpRPfinaaxkjOGc=,iv:NdblfYzGAiX4uaobUkzXHiEmRypqFKXK+/zcDfhzzdU=,tag:Wl3CglfJfzAeODwwZTVtqg==,type:str]
kind: Secret
metadata:
    name: teslamate-postgresql
    namespace: monitoring
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1frds4dglkf9tsnz00zf3tgyxf9q7xxqaeeh44p9dgjeqqfl35a2qxcjcfm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPYXFlUnI4Y2h5QlhKeHdn
            NTQyMkxtVStBQzZmeDZVZnJWWWpQRmYvSEh3ClBscVlBWDdHcGlrWGVqbTZzMWZ4
            NG5TVG4xK3N5VVZOV0FndjV5ZVFOa2MKLS0tIDRLamFsMkkwT2dZQkg5cEF2NmRh
            UTBER2VlaVpUZzFqWTkyeDFUWGFIREUKKUBfkfJM8QXRixmbrdi08p0RBFgr8XjC
            AVBabRFWGo2byWNYTd+NG1CD8ss+TdR7iitLDOPRcQpNuP1y+ndICg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-25T04:46:31Z"
    mac: ENC[AES256_GCM,data:mCm4OR/9xkCxuw21IBu6eGvJtCu1JRSDI54AMIiQtx54fiIlOnvJLtqcAcISt2dSv2i1ncRmyuxWGm4IFOnYDy5nLecpxaHX9LrZneldztKvTsOpsp5m/2ipyJpQIpcZL1bc8GqErcbxKK2HcVH8MN9+YKYNKKY4S90VPxbwPLY=,iv:4S2KUhCp/FgXGc3jiDfYlJduVtgHxwJJQVxqtJ1IcQM=,tag:uz15gyWXXkcyG7GGQ947/w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0