apiVersion: v1
kind: Service
metadata:
  name: port-service-teslamate
  namespace: monitoring
  labels:
    name: teslamate
spec:
  ports:
    - name: teslamate-port
      port: 4000
      targetPort: 4000
      nodePort: 30012
  selector:
    app.kubernetes.io/instance: teslamate
    app.kubernetes.io/name: teslamate
  type: NodePort