apiVersion: apps/v1
kind: Deployment
metadata:
  name: worldmonitor
  namespace: monitoring
  labels:
    app: worldmonitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worldmonitor
  template:
    metadata:
      labels:
        app: worldmonitor
        exposed: nodeport
    spec:
      containers:
        - name: worldmonitor
          image: ghcr.io/koala73/worldmonitor:sha-6c48a33
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          # env:
          #   - name: GROQ_API_KEY
          #     valueFrom:
          #       secretKeyRef:
          #         name: worldmonitor-secrets
          #         key: groq-api-key
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "500m"

---

apiVersion: v1
kind: Service
metadata:
  name: port-service-worldmonitor
  namespace: monitoring
  labels:
    app: worldmonitor
spec:
  ports:
    - name: worldmonitor-port
      port: 8080
      targetPort: 8080
      nodePort: 30019
  selector:
    app: worldmonitor
  type: NodePort