apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: devbox
  namespace: dev
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/domain: devbox
    spec:
      domain:
        cpu:
          cores: 2
        resources:
          requests:
            memory: 4Gi
        devices:
          autoattachSerialConsole: false
          interfaces:
          - name: default
            masquerade: {}
          disks:
          - name: containerdisk
            disk:
              bus: virtio
          - name: cloudinitdisk
            disk:
              bus: virtio
      networks:
      - name: default
        pod: {}
      volumes:
      - name: containerdisk
        containerDisk:
          image: quay.io/containerdisks/fedora:42
      - name: cloudinitdisk
        cloudInitNoCloud:
          secretRef:
            name: devbox-cloud-init
