apiVersion: v1
kind: Secret
metadata:
    name: devbox-cloud-init
    namespace: dev
type: Opaque
stringData:
    userData: ENC[AES256_GCM,data:8iYTf7Hs620omMWwFnGEkHecwd6qp6ISYVJjfO9bp5iW/EuJgKkKVUyNNBIIjKwLxfFsKXbJwEvUH/lyxS3xvxyfEYSNCXnhN30gq9LFF14eF91+IxJy7b/xK9MprqYLraSU9C5rfAZrMPoN87ktHcMS2/5tUcTZnEWT15o/2QYxqQEHQjHEAEfB+3hVh0mGFDR3puSpSEkpr5BbIZvK5zWGtXEz9DK6SHtx5HJQ/EvlEyOXWhBL+XrIVzlO7kvLqpoTpC2nao3aU7LdRBp4L3VHUhclGnShUTTmXBkT2ujnOebJkyZ9ikAg3U6157ErYfzWrRE7L21KNEwZrDh3ZOE0MUubSVACR2X2epWo9hL1wI62LsPrk6Lo/Zo6dE+Mp7IGehyTx45IOwyj5eeKVQh1n8vjX/4qu1YcgZJ5RYpjPkT9MHnGGGns/iX6m3mJB3YWMounDhOmE4fyW6Zd/1GQ8xxEPcCcZGIAgnKctKa2yW/FHoTxsrSWNxL5Cl25Pw2jUwt8xMIcSdpqKyWtCyGxBfyKSgW1mOWECHs+j2cooWSz9nYrBMAfKajCyZhC/IcSDlFgE3u71/RCnfJaASAlLOzgOvyqgHksd870rws4R6wOrA8Uhn358+E9L2fnhK64r9PgiQZpLdp5jM+rCDTmrVjbc2Htf6m/HkekfXIX+RR6ZQa9at4vsYExM2tqFYRntbVWPMgGgvBxfAt+WikqG9jpuUNnnYKr3fkZpwvN86dsRWTCqhxL8uA4xxxH9O9s6Mv5++C0gY1njayDdKtBtJj/0buTMhAleeLsg+LTt8tyF8t3zBcOx5A3fHVlS6MsdF0rgktnNYvGqmfyeVJbF2fIYAYTPEzGCqClG8nSk+B8U8qekkCcsEhy91/HJtpm+VSjisSVGZSzLxSiy/ujkHwL3Wii7akcw638NsUY6vg2JETSMZHdeA6bUOa8JBaQSWGqweJmJNbPxOFaSonuEKzdWey28qCrKeVlaD5nSA4Uez1FTW3v5GMb2ij5oAaSGUp7B7YJI10ny8q8nVovhi/VXXKANgXG0l1mAkQpybMzW7LNU/4lWj6sWic+YAS9s8vdsZB+mipFnDz+0NWepdWBJKLEozzrosS0zDiHJXVKjvn8vLf5twAcWjjBHOaE9anfvrzY2xxaODuR3EIXbP/+DAiKnNEgFEj1Tv03T4y4FShp8vSa5+QpKRNzqjPsIRyHsJy35BMcB802NzIuhgavbeIkfRZAAXMViJuqafrUY/9qLyNvMtgxaqaswIiNY99EAkk6on1NrpiOrQbvvslCjbmjTRt1+Bl4LiswE4Ii8EJDjgm54z7D/GYo3eXTtaj2J8kvhWrqJx4Fb+U5gKRKhjhc44CvAUYsnXVX5gzEQHA+jIoPE05I,iv:Nq/N14kRHmL9a40k/V9rtCFdT4xfFciiae18QdxA3/s=,tag:/CgEwNnZ3mySZxV6tC07Ow==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1frds4dglkf9tsnz00zf3tgyxf9q7xxqaeeh44p9dgjeqqfl35a2qxcjcfm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTRXNUQzZCUU0zR245bXRv
            R1JHanF2eHNEUUtudjFHR29EU2UweHdlQlZjCnpHM0hvOVkxUjR1b1hOaVRKbDlk
            TW16UDNlUXdvQUFacmkyeW5ldlBpUzQKLS0tIFUwVGVrQk5NWHF1SEN3VFJVaUI2
            T2RwVmlKOFZnZmNBNnBqWlpqZHhvMUUKH1p3pEURSCyVrNbv4qFCvfcwvfD7cVgL
            CeAN92bd8hN+n5APwkHcw4T8eIU68JTH5I17Lpt3arKyLVJbXwCtrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T05:26:53Z"
    mac: ENC[AES256_GCM,data:BgNczJSsFHnUyWLaSxCJ9+fqvKLWTjxSipwSyiqEWudQJcSk/ySiC96VOOiSS43Bdb4SCopAOixn1Z/1eU05YpIcmPPgy6GiKaqxO5C55mbalmIYqAYf8vFITtAB8iMy0M484Tg2RtimPWLN7ndFTm57IcID2u8ksymhDz3GgNc=,iv:tJVAXyJvf2BBJ2/X7UfzNPPt7B7bG7FBLzFH4LmKTuk=,tag:njyjbzSC/e2GSrkYk4vDVw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
