apiVersion: v1
kind: Namespace
metadata:
  name: gaming
  labels:
    app: gaming

---

apiVersion: v1
kind: Namespace
metadata:
  name: plex
  labels:
    app: plex

---

apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app: monitoring

---

apiVersion: v1
kind: Namespace
metadata:
  name: compliance
  labels:
    app: compliance

---

apiVersion: v1
kind: Namespace
metadata:
  name: keda
  labels:
    app: keda

---

apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    app: dev