apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: teslamate
  namespace: teslamate
spec:
  interval: 15m
  releaseName: teslamate
  chart:
    spec:
      chart: teslamate
      version: 7.2.0
      sourceRef:
        kind: HelmRepository
        name: teslamate
        namespace: flux-system
  install:
    createNamespace: true
  values:
    image:
      repository: teslamate/teslamate
      tag: 2.2.0
    env:
      - name: TZ
        value: UTC
      - name: DATABASE_HOST
        value: '{{ include "common.names.fullname" .}}-postgresql'
      - name: DATABASE_USER
        value: postgres
      - name: DATABASE_PASS
        value: "{{ .Values.postgresql.auth.postgresPassword }}"
      - name: DATABASE_NAME
        value: "{{ .Values.postgresql.auth.database }}"
      - name: DISABLE_MQTT
        value: "false"
      - name: MQTT_HOST
        value: "mosquitto"

      - name: ENCRYPTION_KEY
        valueFrom:
          secretKeyRef:
            name: teslamate-secret
            key: encryption-key

    ingress:
      main:
        enabled: false

    persistence:
      import:
        enabled: false

    extraVolumes:
      - name: postgres-data
        hostPath:
          path: /root/docker/teslamate/teslamate-db
          type: DirectoryOrCreate
              
    extraVolumeMounts:
      - name: postgres-data
        mountPath: /bitnami/postgresql




    postgresql:
      enabled: true
      image:
        repository: bitnami/postgresql
        tag: "17.6.0"
        digest: ""
        pullPolicy: IfNotPresent
      primary:
        persistence:
          enabled: false
          
      auth:
        existingSecret: teslamate-postgresql
        database: teslamate
        persistence:
          enabled: true
          existingClaim: teslamate-postgres-pvc
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: teslamate
spec:
  interval: 15m
  releaseName: mosquitto
  chart:
    spec:
      chart: mosquitto
      version: 2.4.1
      sourceRef:
        kind: HelmRepository
        name: mosquitto
        namespace: flux-system
  values:
    service:
      type: ClusterIP
      externalTrafficPolicy: null
      annotations: {}
