apiVersion: v1
kind: PersistentVolume
metadata:
  name: teslamate-postgres-pv
  namespace: teslamate
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/server/docker/teslamate/postgres-data
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teslamate-postgres-pvc
  namespace: teslamate
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  volumeName: teslamate-postgres-pv
  storageClassName: ""