# 1. The Bootstrap Issuer (Allows us to self-sign the Root CA)
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}

---
# 2. The Root CA Certificate (The "Police Station")
# This creates the Authority that will sign your other certs.
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-root-ca
  namespace: kube-system
spec:
  isCA: true               # <--- CRITICAL: This allows it to sign other certs
  commonName: "Waffle Root CA"
  secretName: root-ca-secret
  duration: 87600h
  renewBefore: 720h
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer # Signed by the bootstrap issuer from Step 1
    kind: ClusterIssuer
    group: cert-manager.io

---
# 3. The CA Issuer (The "Signer")
# This tells Cert-Manager: "Use the certificate from Step 2 to sign apps."
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: my-internal-ca
spec:
  ca:
    secretName: root-ca-secret # Matches the secret in Step 2

---
# 4. Certificate for the "plex" namespace
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-plex-cert
  namespace: plex
spec:
  isCA: false
  commonName: "*.waffle-k8s.local"
  secretName: wildcard-tls-secret
  dnsNames:
  - "sonarr.waffle-k8s.local"
  - "radarr.waffle-k8s.local"
  - "plex.waffle-k8s.local"
  - "qbit.waffle-k8s.local"
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: my-internal-ca
    kind: ClusterIssuer
    group: cert-manager.io

---
# 4. Certificate for the "infrastructure" namespace
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-infrastructure-cert
  namespace: infrastructure
spec:
  isCA: false
  commonName: "*.waffle-k8s.local"
  secretName: wildcard-tls-secret
  dnsNames:
  - "homarr.waffle-k8s.local"
  - "grafana.waffle-k8s.local"
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: my-internal-ca
    kind: ClusterIssuer
    group: cert-manager.io

---
# 4. Certificate for the "kube-system" namespace
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-kube-system-cert
  namespace: kube-system
spec:
  isCA: false
  commonName: "*.waffle-k8s.local"
  secretName: wildcard-tls-secret
  dnsNames:
  - "hubble.waffle-k8s.local"
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: my-internal-ca
    kind: ClusterIssuer
    group: cert-manager.io