apiVersion: v1
kind: PersistentVolume
metadata:
  name: spire-server-hostpath
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "local-storage"
  hostPath:
    path: /home/server/docker/spire/
    type: DirectoryOrCreate
