apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - nvidia-daemonset.yaml
  - nvidia-runtime.yaml
  - nvidia-time-slice.yaml
  - etcd-backup.yaml
  - cilium-nodeport.yaml
  - cilium-mTLS-pv.yaml
  - cilium-network-mTLS.yaml
  - helmrelease.yaml
  - helmrepo.yaml
  - cilium-loadbalancer-config.yaml
  - cert-manager.yaml
  - cilium-ingress.yaml
  - secret-tailscale.yaml
  - tailscale.yaml
  - unifi-cert.yaml
  - unifi-cron.yaml