apiVersion: apps/v1
kind: Deployment
metadata:
  name: kill-the-newsletter
  namespace: webservices
  labels:
    app: kill-the-newsletter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kill-the-newsletter
  template:
    metadata:
      labels:
        app: kill-the-newsletter
    spec:
      containers:
        - name: kill-the-newsletter
          image: 3nprob/kill-the-newsletter.com:latest
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
            - name: smtp
              containerPort: 2525
              protocol: TCP
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "500m"