apiVersion: v1
data:
    ANONADDY_SECRET: ENC[AES256_GCM,data:kPohDzP+xPN7bMrBFMxgfQolZ3jw81s88P33kXlmv7NcDZ0v8cecgin/BnygP1N/diUvkHeDzXwYP7EOeveizoqJKWkl7w5px1TNongbTGWd+rvxnhVLPw==,iv:Nq4NW0zFbxQqudaZR73vStQsGxROdUEfHv0CCkuduhg=,tag:1dGD9f5ixN8ufvVFrsfzdQ==,type:str]
    APP_KEY: ENC[AES256_GCM,data:RJZLbQcRHk0+aJyOhe1O8TlpsD9TJz+zgsJdpsg4i2DmtpJ++6Uey9gmdqEl7QTKXGydQ//qp3V4Z2EiRLDwzRqmwgI=,iv:C3sDZNHZvUf/59Lcz6/gmyK01AaPsUuVXXloy3KiJ94=,tag:tZu4dsm1ll+MrI67iHEG7Q==,type:str]
kind: Secret
metadata:
    name: addy-io-secrets
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1frds4dglkf9tsnz00zf3tgyxf9q7xxqaeeh44p9dgjeqqfl35a2qxcjcfm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMOWNVVThxZUo1ZncySFAx
            K09GWG1LeXllZnBlQXE4cVMyZVExcnk0LzFNCjd5V0dCMjlwa2lsZjliNUY0SE5n
            Qi9TS0FDR0RNaVRGS1hsNnBXMmdxV1kKLS0tIC9Ccks4RnZlWVhmQ3lqUmd1MnVo
            ZEExeElpb1pRd3M1S2lGcXo2TG90L3cKNOU9/ncxQebh1J5VZ1y7s0L4OHq/8JUm
            /ua2N9OWuytCluUayfyV7KBGgpIt5UYDngk5p2iVe17Fthc80VI/ZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-10T00:09:04Z"
    mac: ENC[AES256_GCM,data:LCKdB26Kcs5OWvgIb5Yz4SAlZW5EKJfe0zhS241Og0RxeTF52mAaqe3h/CPez+Y6cwNhQ2rxq9Ig7tk1IQXjHj/mMWTue855Ey4uv4V73Ym5J9tayeIhSm+UGM/cqeoZ4VBs8VQMbnI6aujtQLjcBpJWZPRypN95iIfFOmm9ZhY=,iv:tfsXdYFJANb+JP4U8Hved8KWjK4H3EDJbFZ82hBbry0=,tag:TOWv7suc5KjNreOM/JJnCA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.