apiVersion: v1
data:
    TS_AUTHKEY: ENC[AES256_GCM,data:0VsziAxyGRIYV1SVFT7ds86oU5B3fDnluBB8ThNz95yeYMEnfzaE0QEGH6LNxNVqOB8OApXI8snuYvPtDkT1SppI/UgQuQB5sBiTyxha47WXUSAA,iv:7MwDvsHOEXJbkJvrRtM/9J+/EdOmJQ18QYMhvt6kAgA=,tag:AFAYals5/GpZeBcnIiOvNg==,type:str]
kind: Secret
metadata:
    name: tailscale-auth
    namespace: masking
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1frds4dglkf9tsnz00zf3tgyxf9q7xxqaeeh44p9dgjeqqfl35a2qxcjcfm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFd3N2WXZ4b01Vd0gvQ1J2
            S1lXSnpuWnBZYXNmeUxCdXlHdjEvakxZSHdBCnBQd2VTeml1aXVQanVEb1N1eFRu
            UmhmZElrcTFSY21wNDZNV20zZzd0NEUKLS0tIDE2TWxJVHVUSjJHcmt1ODdLbTFa
            SURKNk40M3pteEdBb3NlOWZ1VTA3UlUKhlOHsBSpZyaCwA7wOpd+/w3gxqxGWukG
            /99UP1KMXje2NQXYXawKwIJyM0lqGb4XJiuRl9gE2b3PyeeV+s2fgw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T01:50:59Z"
    mac: ENC[AES256_GCM,data:EqNAMQ6rmSHXY1R8b94Jdy5K8sReKjfr4dK2BmdtV9xgU7GZW9OwaZgdIdzF26d8hc55LJx20J4rDA7aLz0Vgy4i4x6cHsUCuyBIM1kHjdTdBwS+VT0mgD7Mz+AdNT0gkSGjwFLFB/Lft6Q6dPsalD4MyxgeJnUvm98G+qArjVc=,iv:ssthWWtGPpTes4nQFAV02k72Oh3k7r/8sv0n4n6SE3g=,tag:OjDLNv2I0D1del5yVBHghA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0