apiVersion: v1
data:
    MAIL_PASSWORD: ENC[AES256_GCM,data:pr2L/HRvdJEHCCfiurXYKAeV13HIrK957MVGAPrB7HMy/MBvBmTk1/JBCO4kqRaa+Kj0RlNwDHxmtFT5nVsWpiaOQyDGXtIv3loqphr3C14fB5IRn6UO3F3la8qPEhaGtJylQd+8lHbWQNGKG5whq3JGHVyh7NQP,iv:xIKTSGXpGUG0isvzGLx60TXHTVG20nnw+Kamyf0TdNM=,tag:E3n1+UueFRPweJPBHH4q9Q==,type:str]
    MAIL_USERNAME: ENC[AES256_GCM,data:tS5U/hX790fC/Vm6Avoqq5C0g4C8vGqr2ovEzwmTKIo=,iv:bxAPduUY4Un1LmQFsS0tXls7fAJJOQxFPZlp0HAhPlw=,tag:fbCwGAcmnIm/qjvvim7GMA==,type:str]
kind: Secret
metadata:
    name: addy-mail-secret
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1frds4dglkf9tsnz00zf3tgyxf9q7xxqaeeh44p9dgjeqqfl35a2qxcjcfm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2T3FXNlY3YXdNZHAwSFoy
            cWJhbzEzU09YcTBLZStxdE84NXVZdGxsaVJZCm9Udm1zNEZ1bDEwcUlpckkwME1G
            UHZsaTVBRUJKM3dQZ2xMd2htNkluMzQKLS0tIFdNazAxUkhrRUdEYWgyc3p2YXZ2
            VFRtM3ErUFN4YUllT0hCaVp5d2ZicU0KrAjfiEt7x1ePb3OrpLVLU/3+x9/9G9Nj
            c30CJKnRHHqUZioKoJg7gL4WlTL3QgN59vxtznBJ/cW7CXw3BZn8xA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-10T21:55:46Z"
    mac: ENC[AES256_GCM,data:hxfhhl6zEDZU6CzOxRDEixP7BhuXZ+P3UutAqfs8SNp/lUVPOOfiBoghD3ehZkZWWKhDfaB03HvDMoOArZ+pQ/as4b/Iz2/Dj73mo73CuaMLCm0hA1Xi+9qIyGcQzJ0mgcRiLUjks0MaF8jZgvEEZM2Z43Xf6wDapEM3euW3L/o=,iv:xbhvw9R+DM5RzkJetoZcEuEzlnSGeh6gYZjTCfKPmfE=,tag:mCXKAiEvbH37YH+tFK0wtA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0