apiVersion: apps/v1
kind: Deployment
metadata:
  name: tailscale-subnet-router
  namespace: masking
  labels:
    app: tailscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tailscale
  template:
    metadata:
      labels:
        app: tailscale
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: tailscale
        image: tailscale/tailscale:v1.96.5
        env:
        - name: TS_ROUTES
          value: "192.168.1.0/24" 
        - name: TS_AUTHKEY
          valueFrom:
            secretKeyRef:
              name: tailscale-auth
              key: TS_AUTHKEY
        securityContext:
          capabilities:
            add:
            # Required for Tailscale to manage networking and routing
            - NET_ADMIN
            - NET_RAW
        volumeMounts:
        - name: tun-device
          mountPath: /dev/net/tun
      volumes:
      - name: tun-device
        hostPath:
          path: /dev/net/tun
