apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: infrastructure-ingress
  namespace: infrastructure
  annotations:
    ingress.cilium.io/force-https: "enabled"
spec:
  ingressClassName: cilium
  tls:
  - hosts:
    - "homarr.waffle-k8s.local"
    - "grafana.waffle-k8s.local"
    secretName: wildcard-tls-secret
  rules:
  # --- Grafana ---
  - host: grafana.waffle-k8s.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: port-service-grafana
            port:
              number: 80
  # --- Homarr ---
  - host: homarr.waffle-k8s.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: port-service-homarr
            port:
              number: 7575

