apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb-pool
  namespace: infrastructure-network
spec:
  addresses:
  - 192.168.1.254-192.168.1.254
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: advertise-all
  namespace: infrastructure-network