apiVersion: v1
data:
    TS_AUTHKEY: ENC[AES256_GCM,data:/bsAvvi1PLSjJ4PKKz1GgTb4cHNclVmTPFVmHxFwFGjOIwULuxBzhJsJpcL7P9W2p3XVPYq9G7lKYzyG0wZEATBTtTrdbos3WWI3x/tR71p1HITr,iv:1PvdDq/ICICAXrqgwXorgm4dRqSz1wVl5tgDTE8g4og=,tag:Bhs6bWC/yk1PzbcAovzrDQ==,type:str]
kind: Secret
metadata:
    name: tailscale-auth
    namespace: infrastructure-network
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1frds4dglkf9tsnz00zf3tgyxf9q7xxqaeeh44p9dgjeqqfl35a2qxcjcfm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSN3lEWVlmTUxKMlJYdmli
            UUUwYjBneU4vdUx6YTRsRE1SMDBYaDRsbHg0CkRxK2VaLzlvMkRlS0Q1RDZqM0R1
            L0t0MnZHVG5uTGxzQ1hRZENUTEMzOFkKLS0tIElJVjRKK1docmMrQjV1MTg2WlhZ
            c3FUVVlNODZtRXlQTDVZOHluS1dmdDgKMqKICIWtdQD51HhvdizMG5zyYQObLO25
            rOMNIbNJstr7V+xH2My4cn5Y6AtJTqVbzRxmM/drFZdJw0OQ3czJUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-09T05:33:15Z"
    mac: ENC[AES256_GCM,data:omd1pxDbKM2QnlsrT6dJAysWu+zJD0bmQx1PgkpPTCSpWfyN7S20O4eLY/QEn5Zdvx8E2XL8jAIdNWKEJp1mlpWjVCR/kAOxdMlL0qzd6H7cJVGkWlgnUfwSweTGa2pVf11vBzMtgRtSIP8QWgrWqqg0NQh4x9N8Q1+m4vzg26k=,iv:xncZkbfTdhWd6UAk8mjJo6g6O0TIF7m4ReSc6MR9QKo=,tag:DmHFirxzn/u9JUV9BJubwg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0