apiVersion: v1
data:
    TS_AUTHKEY: ENC[AES256_GCM,data:0pONYCa06PIFypJgQL3l+TYQIu0Oqr2fAcP0HHW4aH080iz6d0gKGvDx05ypEZ8sHR2K3UkGp755x7X8/ecs/EO9+lzUXnOa7rHy0zzNJwq5ong3,iv:Vf1bbnm8Vvu5cOCtG52PhslTPm+8KseSEibdwboN1UE=,tag:2/YdMJMdueW0dcUMijO1xA==,type:str]
kind: Secret
metadata:
    name: tailscale-auth
    namespcace: infrastructure-network
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1frds4dglkf9tsnz00zf3tgyxf9q7xxqaeeh44p9dgjeqqfl35a2qxcjcfm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxem8vOTk5aEdrR3Vla2tJ
            SzVQUWtoTC9oalBVNGh3b2k0eW1maW1zMmtjCjZOZFVyMkVLVDlZRXJBcDZiOFkw
            WHhuZVEvUDlna3BIbzlWVTZEU01qQVUKLS0tIGtMMjNQMHltRzhrZTFkM2JKM3Za
            TGZYM0FYZTBrbXBWaHN1b0ZLTkF4N1UKTikPfC1g8vib6xOScufQi75PGeKYozrL
            vE/AYlm/wbZBoUC77ji0c5HoFkBGQnb2UsV3Xw2iyBrM5w2ChNhP2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-09T05:42:08Z"
    mac: ENC[AES256_GCM,data:g0tcKWsOHgv+5lyz8EEqsQj9Jiq699stOwshp/Igao3Y4zN6KHLWOscfXdAbFc8Ea0aymOvWYGXwufJowNc8ZbliyDxNSv70VkwLAY1tGgCObwjGmGq/pAuNI+v3aGNcCWEvZ/Df373DO3teHnUwqAOGGv58h8VRSgsTF0UJbJU=,iv:SUuyenOHi8F67iwzTVsuW96Y95BNIQClXa5oy04n99E=,tag:XT2sdhAEEALENJQYEfmS6w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0