apiVersion: v1
data:
    github_token: ENC[AES256_GCM,data:TxiUShOa3mATTSPI/1PhGbrfdEVGXNfUOpXk5R8uYdPpTbWRaC7tK2FEqSSRpQmxe4AKC8F7ioM=,iv:d/bZsu3yEz8DcYbdIimPs9pCG7F876IaGtJTxCUUxfg=,tag:Tqm65H5OnP0rmLXDHc/2XA==,type:str]
kind: Secret
metadata:
    name: github-arc-auth
    namespace: dev
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1frds4dglkf9tsnz00zf3tgyxf9q7xxqaeeh44p9dgjeqqfl35a2qxcjcfm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIdHRrM0FiZ3ZXREFxdnlx
            WmFXcFhsZ0JIaStLdG1jTitGUWswNStLbTJJCnJvMVNIRG5keFJTQWI4ejNYQXZk
            Um11dEZod2w5b3dOL0loNGQ0UGxVZ3MKLS0tIDhxMjNKWWdNVUxDVDUveFFuQVNk
            UFI4Mjc3SWY3ZitseTdlQ0VMZExmdk0KlQ1LDQYtX9p+tHYtC8pW3rzDxWUq4mA+
            xDEQwlr1xt3DkC1xtib0sCt2dO0yuAzgHwkM7SFW2Iv9Qk/0Ii+QSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-01T23:03:02Z"
    mac: ENC[AES256_GCM,data:WM2xvKzvevFTMpKQ0np2nbI9kFeN2pFUYGj9OqmbqfasQJ3gtRrTB+C5oEgj6kecLobxfYH10JU8xUfwgzxE99jHNpTlhibf0dREg9crY0otZJYHQ99aw56riG0SYaf8JyTRWhCeypxXCgBFVeZkgxiAxqL17Nw1gDnrZ2lxXIY=,iv:UzG9aWV/xCoE604FClrYwNyV1T0G+A+sVmyE6HMRrCw=,tag:IA5iDvjz9WTLvQrWW33JFQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0