apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
      - name: ollama
        image: ollama/ollama:latest
        ports:
        - containerPort: 11434
        volumeMounts:
        - name: ollama-data
          # This is the default path where Ollama stores models inside a Linux container
          mountPath: /root/.ollama
        resources:
          limits:
            nvidia.com/gpu: 1
      volumes:
      - name: ollama-data
        hostPath:
          path: /home/server/docker/ollama
          type: DirectoryOrCreate

---

apiVersion: v1
kind: Service
metadata:
  name: ollama-service
  namespace: dev
spec:
  selector:
    app: ollama
  ports:
    - port: 11434
      targetPort: 11434