apiVersion: v1
data:
    TWELVE_DATA_API_KEY: ENC[AES256_GCM,data:i7JP6SAft9+V+mVXwfHn49X7DevL/24tLDoXcCuNATwVuzDipXaRUyzV9g0=,iv:ZV11KNtjgI4nu87FAS9ixtoO29S01WKERMCgYLLMVfc=,tag:nlmlb7ZD+ubI5ZuVP1VATQ==,type:str]
kind: Secret
metadata:
    name: finance-friend-secret
    namespace: dev
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1frds4dglkf9tsnz00zf3tgyxf9q7xxqaeeh44p9dgjeqqfl35a2qxcjcfm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqVHZpUlZjUFRnTnZoTU0w
            KzRwQkVqL2dkNFQ5QkxNcHV4M1dyODVuSUhZCk9RSTN5L1djcjBDbUhRckpqUSsr
            eWdxenFRaklLZURsTUxrMy9WbmUxZ0kKLS0tIENlUUdIcUs0cXJtZzIwMk1pMVNp
            N1ZuU010aVJHWWpPckhkMmxrMTBVazQK3B5I5ABUdzKsK55MD+2NEzwVAvE3b635
            Pl632VDy8si5JBBGIO11j9ZKCOmNX5EofNmM+atpTMDy5FLLZn8cyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-30T03:11:06Z"
    mac: ENC[AES256_GCM,data:ortW9ViVXH4QVEVI+VGYupxhsvIA+z5RN2xH96rShjHGLdEGg2pGp7RJN+zm3plybs8m/WGIZf+4tN46XGQtPU3ly+hKrmxG8OJCWdKYBG9wsgFZcDH0HZ7mquMOUvRiUK3D1WiW3ZmUPurAoE7z10+2TdyQ0ThppAaAO/D2l3I=,iv:jJrhNHlQ9u2WG13L6ZTl6x0D8tMfoc20r+/5t/ep8eQ=,tag:bvUzG/KBdms3RpiZTDmBiw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0