apiVersion: v1
data:
    CENSUS_API_KEY: ENC[AES256_GCM,data:zv1qI+s+W5HOzZOuxftuSCJUSHBjTQjFhrMAfHDi/6BlC7BODRrgGBNZuO6ExdByUhJlVth6V8Q=,iv:A3kpVRYhe/o/lsVff1hd8iuIjlABPjfvMou8ui0k4Jw=,tag:mvqWfYaxJAinsDT8V5WHBA==,type:str]
kind: Secret
metadata:
    name: finance-friend-secret
    namespace: dev
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1frds4dglkf9tsnz00zf3tgyxf9q7xxqaeeh44p9dgjeqqfl35a2qxcjcfm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFRW04K3M0VnRUY1M5ZDkw
            NTIwc1hRNXFPSkE0ZWR5Z1lqZzFzZEF3OVFvClVETlhpUTBsbGY2KzViS3ZGS0Fp
            R3FUenl2a3hkaXVWejFreHFxNWxPeTgKLS0tIEdGejFobjBWZGlKWlZWUC9Ga245
            dys4ZzBUdHVKdkZRUEduZEFTbG5yaTgKS+uIIi/w4mYxN9W0gduNSQL074Pxfmxv
            4WyRaTuOcvPq3c71VkQMTg1PWTKdoz/jU6h9sSxHxgdXsaxbRxuLoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-03T03:45:30Z"
    mac: ENC[AES256_GCM,data:FEXKvBoKT51lbQcDXHkw3jfSypPEqf3UORMN+LNILwbtJiZJRzY6usP8+kr7btzwKBNHQcB1Oo4lqbY3l/AR2bPNCNx0BYJDuF6RDWwqH2EGXsvm+V2PHufCth3o0lKdTODAVDvhszz0p/dl3wOTjvGbpYNVYuFDZOfMIncPFOk=,iv:zwFEQVtg4Z86wGzFxTGXXY5g8fvLhrQo+lLRvugRxOM=,tag:HzOZrnyuEmkmSoPJDI//CA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0