apiVersion: apps/v1
kind: Deployment
metadata:
  name: market-re-db
  namespace: investing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: market-re-db
  template:
    metadata:
      labels:
        app: market-re-db
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_DB
          value: trading_intelligence
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres
              key: POSTGRES_PASSWORD
        ports:
        - containerPort: 5432
          name: dbport
        volumeMounts:
        - name: db-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: db-storage
        hostPath:
          path: /home/server/docker/investing
          type: DirectoryOrCreate

---

apiVersion: v1
kind: Service
metadata:
  name: market-re-db-service
  namespace: investing
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: market-re-db
