apiVersion: v1
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:lLcBO26e+maNCGm1D6m4CQ==,iv:fvVu/1Z8S4hSkFDWzrxbPGXhsy4qwbnwhvTrG2oOsf8=,tag:xwHuFE+xIM7GC9V1tPJ8Yg==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:s42vGU+531o=,iv:DX+srYpG3EdekOp8qTlTDCwRKnXeOidHwGn4njouKiU=,tag:b3du4mG6i46TI6dxkgc3HA==,type:str]
kind: Secret
metadata:
    name: postgres
    namespace: investing
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1frds4dglkf9tsnz00zf3tgyxf9q7xxqaeeh44p9dgjeqqfl35a2qxcjcfm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsZVQ1SnkzdDNEN0dicS9s
            bUlPN1U2bUJ5cVh1UWh5WTJyZVhHdFRwZUZZClc2RUpzK2UzTG90VjBWaU5zVyt5
            N1M2S3ZLM3VUc04yZGVLYWh4cTdFWGcKLS0tIDF1RjlVVHpQWFZERVRMRmUwLzBq
            Y1lrREl3bktrTTNBVld6amg0eWo2cVUK0sitnEfNpRza+Pj9VXnDnS1BZGHzVFMU
            WCuLaSHUPLXodB/wPzx5/UFINixeFmyYjNsOJ8V5xKlJ8cR3uA9vsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-17T03:03:10Z"
    mac: ENC[AES256_GCM,data:Z6lhR8k05A8E51SHTjHW8M76awzQ1typN1nxsqMySdMDLr0wR+r3o2XJ3Cum/M5ZBTQ6TRPNlcfTSXE8fJuJDYdNKXrYzXvZt2c8q1vMKRy9SpV4DQXSvekxEVvux6OIVtM01TrNfa0DhpdYypWiSiZ3+iveomavgcaqmfrZVyM=,iv:FIYAzQjXLaVUfkVzyNITe/zi6vERqj2Jl7a6SzPXpKY=,tag:orVmxZH2P75dPIYN/AlPPw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0