apiVersion: v1
data:
    GEMINI_API_KEY: ENC[AES256_GCM,data:ooeQAJqOK0S41BGgVohmGz7dNRTrPvIlLnn/TIzP9MFZuahoPUoFZztGRp/8U72j6xoSfJjt78Nxt65/w7/eb3freO+ev06A,iv:UlDNJ+A2iSgdhR9FtxqKQqZraDXVVGZyPPZfpAOcdu0=,tag:ohTeHjVyLwKIZrLLInIRwQ==,type:str]
kind: Secret
metadata:
    name: gemini-api
    namespace: investing
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1frds4dglkf9tsnz00zf3tgyxf9q7xxqaeeh44p9dgjeqqfl35a2qxcjcfm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvVnJqWEtFbXFCUysvZm5J
            aFdnbHBpNFAxZnR4bWUzN29wVCsvTXFHbmtRCk15a1gxcW0zenVML3IzK3RoL2lC
            b1AvcTJ5RWNISnA3eEVEY2lIekNrZzgKLS0tIC9RV2htejlJUEtQUlkzUGxpRjUv
            YldUL2RTTUtRbkZPeXdyemhSS1JHUmMKUu6WTYFUzvIo5ZGT067lZdxH86slyV9H
            WIlgR1UnPwHn6CDN6V2VroHVBsKOm1sMt72wjGFj3Jbic/wy0AGUmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-17T03:06:19Z"
    mac: ENC[AES256_GCM,data:cxYjggMBYcHwm4ZrWewWUROqHcfOl2ZDIuGTBSzY6SD14JCxpISDrRUEZ/Et9Wzlo3SxGIDOxeYz2pmjsN4yNQ7hveJtSVmBD2vkGvG4tmgSunitL/e/eCNdqdn6ofkjtxQxwlyJogQGuCmbwetbyTETNK/gTytlB8Kjul+srWo=,iv:+H2qy0m/WiY9NKAFHY8J+OnaGNNG1sCUHuXXraRtRe8=,tag:A9porYKuCyZ653oLnOETOw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0