apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - homarr.yaml
  - image-policies.yaml
  - image-repositories.yaml
  - image-update-automation.yaml
  - helmrelease.yaml
  - helmrepo.yaml
  - grafana-nodeport.yaml
  - secret.grafana.yaml
