apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:kFjTqmevHKP932x63ZpRtQ==,iv:R08ICMPT8rq4ojvoOAq+bx8r3nqBXh1HkDfYCcRYTyc=,tag:L7ivJHmrTqOvZS4IocXm1Q==,type:str]
    admin-user: ENC[AES256_GCM,data:ocQ3VgRbC1w=,iv:H/q9WjkwhyyZnrU/5VG1Tq8a4AOPJLtMGWW6XhQ9ups=,tag:Dlbdl2C1e1pOcbi5BuR2FQ==,type:str]
kind: Secret
metadata:
    name: grafana-admin
    namespace: infrastructure
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1frds4dglkf9tsnz00zf3tgyxf9q7xxqaeeh44p9dgjeqqfl35a2qxcjcfm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRN000RHZWYUJ4M2d4U2pM
            V3Y4RW04anBvTEsvYlhqNGs4OUZneTRFVFJBCkpFblcrV3pUdmNadmFjQWc2c0Vq
            eXR1dEp1MjhaNFVpbk9ja1V3MGxkcncKLS0tIGtPZ0s1MFRISUpmNDdQeTF2RDhD
            NUUxdEExaDhvb29pUzBveXNlZHliSDgKLcqu3pWA0XpGN6fwSir3wWuHaswPwXwt
            OfGwtGPbkNnLCTyqGhSKL7bxCLBA2q7I3aqonRWyYoci2F4bd83dxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-23T02:32:35Z"
    mac: ENC[AES256_GCM,data:c3Ly9sK+2CXClGj746xF+I5+MacRHHDHaoY3maU81b0xksbQdxAs+i6QLHfRa+kbXFi02VO7X/AAoO3X3RVI6fXk4wiEn56sBH/OfwESNsvMvHuSLE5WGqw9Jd8/yQwYc8+tpZdplO9R4fma7iUzQ0baH0mSmC80tzemLrkFVEI=,iv:ozdRDda2A8q06uG4p+Y3e7fSfid6WmfaZgEGoUYkYR0=,tag:M/vXPYDlddYl+iqPgP8H2A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
