apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./admin-namespaces
  - ./teslamate
  - ./gaming
  - ./infrastructure
  - ./infrastructure-network
  - ./kubevirt
  - ./plex
  - ./trivy-system
  - ./kube-system
  - ./masking