apiVersion: v1
kind: Service
metadata:
  name: minecraft-service
  namespace: gaming
spec:
  type: NodePort
  ports:
  - name: minecraft-port
    port: 25565
    targetPort: 25565
    nodePort: 30016
  selector:
    app: minecraft
    
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server
  namespace: gaming
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      restartPolicy: Always
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: mc
        image: itzg/minecraft-server:java21
        resources:
          limits:
            memory: "16000Mi"
        ports:
        - containerPort: 25565
        env:
        - name: EULA
          value: "TRUE"
        - name: MEMORY
          value: "10G"
        - name: TYPE
          value: "NEOFORGE"
        - name: VERSION
          value: "1.21.8"
        - name: DIFFICULTY
          value: "3"
        - name: SEED
          value: "-8395554130348605121"
        volumeMounts:
        - mountPath: /data
          name: mc-data
      volumes:
      - name: mc-data
        hostPath:
          path: /home/server/docker/minecraft
          type: Directory
