apiVersion: v1
data:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:1l5zPIHZZ9U=,iv:5d/twJMWxfHGRuNgzzmY+yBfJxDDvA8zwOIgUfX3Y+4=,tag:3dTGdnzFFz9jE9H6fDOQ3g==,type:str]
kind: Secret
metadata:
    name: project-zomboid
    namespace: gaming
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1frds4dglkf9tsnz00zf3tgyxf9q7xxqaeeh44p9dgjeqqfl35a2qxcjcfm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxdS9JaDZyc0o4d2crZHZH
            ZHZOamhRZEFIb2tjK01HTTVwVUdHbHNxSlI0CnZIK3I1MUZOQllsYy9MbzdxSnJX
            Q2Nvem93emE5bVFFZ3ZnSnBhS1VhMXMKLS0tIHR5OCt5bU1taVFQWllZYW5mcXJX
            VWk5SDFwRGs1a0lta3J0Umk0WjAwODAKSG2PheUaMH6mFMylWCkWY4K4ekaNZZ5M
            ut77SFSsM4x6p2BBahnah8p6sxDPEGeJx+HFyez3YbvLdW2RA8NstQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-04T03:59:35Z"
    mac: ENC[AES256_GCM,data:/x2zLa+lLAhpkQJeP3u1Yuc7cnbpp2MBeKH4VvR07I8ePQ+KO0s69aKMQesfjFwd392qv5+7CK49CzXOgfroVqcFTfVaJJKcoVMA1V/l/0JKvowzws2W40bZVUe0k+gt4Z0ZCY9hHaQ/BKYobW9BWObavrVeMAM4Sru+9LP3wck=,iv:FStLQGDtc9Ai7j65lozFnmlI2EV2ZzRTe5xPUlcCVAc=,tag:u8hWTlWniI4r44XMStsMNg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0