apiVersion: v1
data:
    subdomain: ENC[AES256_GCM,data:PuhX57TWrgAGpg+MVAtUrA==,iv:VRFPWuOikpGr1/SxD/09ggw6cuWXUaKKBc6B20WPoJA=,tag:bF9cA/PEqp10CPZL+wCQvw==,type:str]
    token: ENC[AES256_GCM,data:NhZJNjsL5AVQq/xiWl/0CezFPBk74fnC3aypsvIkv6gky2opC5TYJ52yXXxz1qko,iv:1p3eOZz93DyE/guAtJnhC91HwcttEsDKcTPeDhdrdt4=,tag:F6zesoth7Hu/hfE/VYbgLQ==,type:str]
kind: Secret
metadata:
    name: duckdns-secret
    namespace: gaming
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1frds4dglkf9tsnz00zf3tgyxf9q7xxqaeeh44p9dgjeqqfl35a2qxcjcfm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCVHJhY0kvQ2ZWaThkOG9U
            blY3NUQ5QTBQVnhsaklTM0JKMktucnliVzBJCjQwYjBZZnJNcnMrMDRCemVTK2NT
            c1JGa0xNVzIveDNRbHd1dWJwQnZod3cKLS0tIHdRc3QvdlAxSGIxQUlnUlFuU1JW
            V2VlUzA2R3lXdEp2ME5jKzJ1VjA2bVkKGKhE9PI5IWkTfriNZwWKB/I5apb6qaSc
            1g4ubhrxeXUgq8u4avEJ0TqofnqHN/N/IRunOrszCli10vtuAoZMTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-23T01:03:02Z"
    mac: ENC[AES256_GCM,data:LLUN1K7K0DizkG5FJMwza9CcaK5zQHyri27ZL7E9RpkiBGjgHrjmbucjVLmaL6wRLIUcWi7G1RBr1ih6xrNidZaAjd6z2YWJ9qVkqJuE3YG6gtfd+YCRDpANkUInvLDDMnWDm6z/m/CioWWJ02tqzajp7VAh/P1HcveZsvWAhE4=,iv:yHEP5wkwqSVnXpfKtY9B/lCrlgf7xhXxiqWfDvtTAOY=,tag:Ii6jM39yoRZne0rMOkQ3Sg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
