apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-friend
  namespace: dev
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
        exposed: nodeport
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: web
        image: ghcr.io/jacobmyers98/finance-friend:1.0.0 # Replace with your actual web image (e.g., your-dockerhub-user/web-app)
        ports:
        - containerPort: 80 # Replace with the port your application actually listens on

---

apiVersion: v1
kind: Service
metadata:
  name: port-service-finance-friend
  namespace: dev
  labels:
    app: web
spec:
  type: NodePort
  selector:
    app: web # This links the Service to the Deployment above
  ports:
    - port: 80 # The port the service exposes internally within the cluster
      targetPort: 80 # The port the container is listening on (must match containerPort above)
      nodePort: 30024 # Optional: Hardcodes the port on the host nodes (must be 30000-32767). Remove this line to let K8s assign a random port.
