apiVersion: v1
data:
    runner-token: ENC[AES256_GCM,data:Bapasj69rW5QzE4gBPIr5CVm3lFLaoxB0Os1qXK0SI9qDgojiWA/NA==,iv:7zPiZnytJ9i6InfbpaMOa83vhWdjgM1PiL9eW79+Cg4=,tag:huti9nakSYpCH93kJOjNqQ==,type:str]
kind: Secret
metadata:
    name: gitlab-runner-secret
    namespace: gitlab-runner
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1frds4dglkf9tsnz00zf3tgyxf9q7xxqaeeh44p9dgjeqqfl35a2qxcjcfm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2MTRGNm9tMVFvUkVmRzBm
            UVhBYmYra3QzZG9CRjY1Q1FGMi84d0FYUUdvCjlqak5ocFlHU0U2VHFtSUtTdG0w
            bUJzRFI2Si9CWmtEeThpekt3Z0wrblkKLS0tIFQ4MkcvOE0xREV2SUMzanNCNGph
            M0FQOU1OUDZnY3Nma3VCV3RTbXZoclUKRy4GqRYWjWmdP/z7vMGxJHzlM4NzES05
            5dDk0cWZSItZevLkO11jBpmPlBAUTJ02qvNQu3jkV6KZrsY0cAMVfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-01T22:36:11Z"
    mac: ENC[AES256_GCM,data:aGigy+xQ2SUl1Sfp4c5QQTT3gYz9XFfL7zvcro2Ur0ZiIdpZTg68P4oPJ9iKo3l7HvQcru+3Az9abMXAPJA6V3RgRDxG+mnaHGH2ZjAk0I4Pxizw5yOJEefI2MVzwqPNlYhohP+zO35vAIpQi7BmXCO4/Cg0D4koIeWZszywqFk=,iv:w+Pabj3OMMWZ8KeYt0lmQKsfZr/zI2NtETEEMy5u7BI=,tag:tCgkd5tq0dw7sXB8RujKIQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0